### ISSUE TITLE
dataset unavaiable

### ISSUE THREAD

**Issue by Oran-Ac** [zzaebok/sparkle#1]
Hi,

Thanks for your fantastic works. It's quite inspiring. However the link in the README.md for the dataset are all invalid. Could you update them or share them with me?

Thanks so much:)

**Comment by zzaebok** [comment]
Hi Oran, sorry for the late replying 😢
I will take care of the issue ASAP!
Thank you for the reporting.

**Comment by zzaebok** [comment]
@Oran-Ac We've fixed the issue. Can you check the downloadable link again please? Let me know if you encounter any other issues!! :)

**Comment by Oran-Ac** [comment]
Thanks so much. It works now 😄
